language: python
python: 2.7

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds

before_deploy:
  - 'curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"'
  - 'unzip awscli-bundle.zip'
  - './awscli-bundle/install -b ~/bin/aws'
  - 'export PATH=~/bin:$PATH'

install:
  - "pip install lektor"

script:
  - "lektor build"

deploy:
  provider: script
  script: "lektor deploy s3"
  on:
    branch: master
